
export interface solicitudesAduanas {

    no: number,
    audiencia: string,
    fechaAudiencia: Date,
    NIT: string,
    nombre: string,
    noDuca: string,
    noDucaOrden: string,
    fechaAceptacion: string,
    regimen: string,
    selectivo: string,
    paisProveedor: string,
    tipoAjuste: string,
    expedientes: string,
    certificadoensayo: string,
    dictamenArancelaria: string,
    fechaDictamen: Date,
    Descripcion: string,
    capituloDeclarado: number,
    partidaDeclarada: number,
    incisosDeclarado: number,
    tasaDai: number,
    daiPagado: number,
    ivaPago: number,
    tratoArancelario: string,
    capituloDictaminado: number,
    partidaDictaminado: number,
    incisoDictaminado: number,
    tasaDaiaDictaminado: number,
    tipoAlertivo: string,
    opinionDace: string,
    montoTotal: number,
    observaciones: string,
    unidadMedida: string,
    cantidad: number
    valorDeclarado: number,
    valorAjustado: number,
    numeroOrden: string
}
